### ISSUE TITLE
Update for CMS Version 2.2.x please

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [MonkeyOnKeyboard/steamauth#5]
Please Update this Module to the latest version of ilch cms please if you can. Thank you in advance.

Regards

**Comment by MonkeyOnKeyboard** [comment]
Hello, thanks for your issue.
If updated the steamauth to 2.2.0 core. please try it. it must be run.
i cant test the update process, because i have an new installation of ilch on my testbench

**Comment by TheFrozenThr0ne** [comment]
Ah alright ok thank you very much for it. It works. :)
